// Tutorial followed: https://www.youtube.com/watch?v=Y9Iam4fZ0O4

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator;

/**
 *
 * @author stcychn
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    double numEnter1;
    double numEnter2;
    double result;
    String op; // operator
    
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtResult = new javax.swing.JTextField();
        jbtnPM = new javax.swing.JButton();
        jbtnBS = new javax.swing.JButton();
        jbtnCE = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtnplus = new javax.swing.JButton();
        jbtndigit7 = new javax.swing.JButton();
        jbtndigit8 = new javax.swing.JButton();
        jbtndigit9 = new javax.swing.JButton();
        jbtnminus = new javax.swing.JButton();
        jbtndigit4 = new javax.swing.JButton();
        jbtndigit5 = new javax.swing.JButton();
        jbtndigit6 = new javax.swing.JButton();
        jbtnmulti = new javax.swing.JButton();
        jbtndigit1 = new javax.swing.JButton();
        jbtndigit2 = new javax.swing.JButton();
        jbtndigit3 = new javax.swing.JButton();
        jbtndivi = new javax.swing.JButton();
        jbtndigit0 = new javax.swing.JButton();
        jbtndeci = new javax.swing.JButton();
        jbtneq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtResult.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtxtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtResult.setActionCommand("<Not Set>");
        jtxtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtResultActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 40));

        jbtnPM.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnPM.setText("±");
        jbtnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPMActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 60, -1));

        jbtnBS.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnBS.setText("←");
        jbtnBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBSActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, -1));

        jbtnCE.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnCE.setText("CE");
        jbtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCEActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 60, -1));

        jbtnC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 60, -1));

        jbtnplus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnplus.setText("+");
        jbtnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnplus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 60, -1));

        jbtndigit7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtndigit7.setText("7");
        jbtndigit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, -1));

        jbtndigit8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtndigit8.setText("8");
        jbtndigit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 60, -1));

        jbtndigit9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtndigit9.setText("9");
        jbtndigit9.setToolTipText("");
        jbtndigit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit9ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 60, -1));

        jbtnminus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnminus.setText("-");
        jbtnminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnminusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnminus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 60, -1));

        jbtndigit4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtndigit4.setText("4");
        jbtndigit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, -1));

        jbtndigit5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtndigit5.setText("5");
        jbtndigit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 60, -1));

        jbtndigit6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtndigit6.setText("6");
        jbtndigit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 60, -1));

        jbtnmulti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnmulti.setText("*");
        jbtnmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmultiActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnmulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 60, -1));

        jbtndigit1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtndigit1.setText("1");
        jbtndigit1.setToolTipText("");
        jbtndigit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 60, -1));

        jbtndigit2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtndigit2.setText("2");
        jbtndigit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 60, -1));

        jbtndigit3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtndigit3.setText("3");
        jbtndigit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 60, -1));

        jbtndivi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtndivi.setText("/");
        jbtndivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndiviActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndivi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 60, -1));

        jbtndigit0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtndigit0.setText("0");
        jbtndigit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit0ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 60, -1));

        jbtndeci.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtndeci.setText(".");
        jbtndeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndeciActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndeci, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 60, -1));

        jbtneq.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtneq.setText("=");
        jbtneq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneqActionPerformed(evt);
            }
        });
        getContentPane().add(jbtneq, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNumbers(String q)
    {
        String nums = jtxtResult.getText() + q;
        jtxtResult.setText(nums);
    }
    private void jtxtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtResultActionPerformed

    private void jbtnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPMActionPerformed
        double nums = Double.parseDouble(String.valueOf(jtxtResult.getText()));
        nums = nums * (-1);
        jtxtResult.setText(String.valueOf(nums));
    }//GEN-LAST:event_jbtnPMActionPerformed

    private void jbtnBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBSActionPerformed
        String bksp = null;
        if (jtxtResult.getText().length() > 0) {
            StringBuilder sb = new StringBuilder(jtxtResult.getText());
            sb.deleteCharAt(jtxtResult.getText().length() - 1);
            bksp = sb.toString();
            jtxtResult.setText(bksp);
        }
    }//GEN-LAST:event_jbtnBSActionPerformed

    private void jbtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCEActionPerformed
        jtxtResult.setText("");
        String firstnum, secondnum;
        firstnum = String.valueOf(numEnter1);
        secondnum = String.valueOf(numEnter2);
        
        firstnum = "";
        secondnum = "";
    }//GEN-LAST:event_jbtnCEActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtResult.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplusActionPerformed
        numEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        op = "+";
    }//GEN-LAST:event_jbtnplusActionPerformed

    private void jbtndigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit7ActionPerformed
        EnterNumbers("7");
    }//GEN-LAST:event_jbtndigit7ActionPerformed

    private void jbtndigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit8ActionPerformed
        EnterNumbers("8");
    }//GEN-LAST:event_jbtndigit8ActionPerformed

    private void jbtndigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit9ActionPerformed
        EnterNumbers("9");
    }//GEN-LAST:event_jbtndigit9ActionPerformed

    private void jbtnminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnminusActionPerformed
        numEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        op = "-";
    }//GEN-LAST:event_jbtnminusActionPerformed

    private void jbtndigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit4ActionPerformed
        EnterNumbers("4");
    }//GEN-LAST:event_jbtndigit4ActionPerformed

    private void jbtndigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit5ActionPerformed
        EnterNumbers("5");
    }//GEN-LAST:event_jbtndigit5ActionPerformed

    private void jbtndigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit6ActionPerformed
        EnterNumbers("6");
    }//GEN-LAST:event_jbtndigit6ActionPerformed

    private void jbtnmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmultiActionPerformed
        numEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        op = "*";
    }//GEN-LAST:event_jbtnmultiActionPerformed

    private void jbtndigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit1ActionPerformed
        EnterNumbers("1");
    }//GEN-LAST:event_jbtndigit1ActionPerformed

    private void jbtndigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit2ActionPerformed
        EnterNumbers("2");
    }//GEN-LAST:event_jbtndigit2ActionPerformed

    private void jbtndigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit3ActionPerformed
        EnterNumbers("3");
    }//GEN-LAST:event_jbtndigit3ActionPerformed

    private void jbtndiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndiviActionPerformed
        numEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        op = "/";
    }//GEN-LAST:event_jbtndiviActionPerformed

    private void jbtndigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit0ActionPerformed
        EnterNumbers("0");
    }//GEN-LAST:event_jbtndigit0ActionPerformed

    private void jbtndeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndeciActionPerformed
        if (!jtxtResult.getText().contains(".")) {
            jtxtResult.setText(jtxtResult.getText() + jbtndeci.getText());
        }
    }//GEN-LAST:event_jbtndeciActionPerformed

    private void jbtneqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneqActionPerformed
        numEnter2 = Double.parseDouble(jtxtResult.getText());
        if ("+".equals(op)) {
            result = numEnter2 + numEnter1;
        }
        else if ("-".equals(op)) {
            result = numEnter1 - numEnter2;
        }
        else if ("*".equals(op)) {
            result = numEnter2 * numEnter1;
        }
        else if ("/".equals(op)) {
            result = numEnter1 / numEnter2;
        }
        jtxtResult.setText(String.valueOf(result));
    }//GEN-LAST:event_jbtneqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnBS;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCE;
    private javax.swing.JButton jbtnPM;
    private javax.swing.JButton jbtndeci;
    private javax.swing.JButton jbtndigit0;
    private javax.swing.JButton jbtndigit1;
    private javax.swing.JButton jbtndigit2;
    private javax.swing.JButton jbtndigit3;
    private javax.swing.JButton jbtndigit4;
    private javax.swing.JButton jbtndigit5;
    private javax.swing.JButton jbtndigit6;
    private javax.swing.JButton jbtndigit7;
    private javax.swing.JButton jbtndigit8;
    private javax.swing.JButton jbtndigit9;
    private javax.swing.JButton jbtndivi;
    private javax.swing.JButton jbtneq;
    private javax.swing.JButton jbtnminus;
    private javax.swing.JButton jbtnmulti;
    private javax.swing.JButton jbtnplus;
    private javax.swing.JTextField jtxtResult;
    // End of variables declaration//GEN-END:variables
}
